### PR TITLE
updates for proxy support, pin rake version for errors

### PR DESCRIPTION
**Pull request by pdaugavietis**
PR for #37

### CODE REVIEW

**Comment by pdaugavietis** [comment]
To get tests to pass, had to bump the ruby versions by a few (see https://travis-ci.org/flowdock/flowdock-api/jobs/213533082#L207) and seems there is a known issue with rake that needs pinning < v11 (https://travis-ci.org/flowdock/flowdock-api/jobs/231974189#L188)

**Comment by pdaugavietis** [comment]
Oh - and mock needed updates to NOT use token in URL, but passed with BASIC <token> in Authorization header (https://travis-ci.org/flowdock/flowdock-api/jobs/231977632#L196)

**Comment by pdaugavietis** [comment]
Any chance this is going to be merged in?    I'm running my own version of gem now for a while...  I'd like to push to general population...

**Comment by srmelody-rally** [comment]
hey thanks @pdaugavietis for your contribution!

**Comment by mahdification** [comment]
Nice!

**Pull request merged**
